import { useState, useRef, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea"; // Assuming Textarea component exists
import { Sparkles, Loader2, Send, Bot, User, ArrowLeft } from "lucide-react";
import { api } from "@/lib/api";
import { useToast } from "@/hooks/use-toast";

interface Message {
    role: "user" | "assistant";
    content: string;
}

const AiSurveyAssistant = () => {
    const navigate = useNavigate();
    const { toast } = useToast();
    const [messages, setMessages] = useState<Message[]>([
        {
            role: "assistant",
            content: "👋 Hi! I'm your AI survey assistant powered by Llama 3.1. Tell me about the survey you'd like to create.\n\nWhat's the purpose? Who's your target audience?\n\nWhen you're ready, just say 'done' and I'll generate the questions for you!"
        }
    ]);
    const [input, setInput] = useState("");
    const [isChatting, setIsChatting] = useState(false);
    const [isGenerating, setIsGenerating] = useState(false);
    const messagesEndRef = useRef<HTMLDivElement>(null);

    useEffect(() => {
        messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
    }, [messages]);

    const handleSendMessage = async () => {
        if (!input.trim() || isChatting) return;

        const userMessage = input.trim();
        setInput("");

        // Add user message to chat
        const newMessages = [...messages, { role: "user" as const, content: userMessage }];
        setMessages(newMessages);

        // Check if user said "done"
        if (userMessage.toLowerCase().includes("done")) {
            setIsGenerating(true);
            try {
                const result = await api.generateSurveyFromChat(newMessages);

                if (result.error) {
                    toast({
                        title: "Generation failed",
                        description: result.detail || "Failed to generate survey",
                        variant: "destructive",
                    });
                    setMessages([...newMessages, {
                        role: "assistant",
                        content: "I encountered an error generating the survey. Please try again or contact support."
                    }]);
                    return;
                }

                // Navigate to editor with generated data
                navigate("/survey-editor", {
                    state: {
                        surveyData: {
                            title: result.title || "AI Generated Survey",
                            description: result.description || "Generated by AI Assistant",
                            questions: result.questions.map((q: any, idx: number) => ({
                                id: `${Date.now()}-${idx}`,
                                type: q.type || "text",
                                text: q.text,
                                required: q.required !== undefined ? q.required : true,
                                options: q.options,
                            })),
                        },
                        template: "standard", // Default template
                        fromAI: true
                    },
                });

                toast({
                    title: "Survey Generated!",
                    description: `Created ${result.questions.length} questions. You can now edit them.`,
                });

            } catch (error: any) {
                toast({
                    title: "Error",
                    description: error.message || "Failed to generate survey",
                    variant: "destructive",
                });
                setMessages([...newMessages, {
                    role: "assistant",
                    content: "I encountered an critical error. Please try again."
                }]);
            } finally {
                setIsGenerating(false);
            }
            return;
        }

        // Continue conversation
        setIsChatting(true);
        try {
            const response = await api.chatWithAI(newMessages);

            setMessages([...newMessages, {
                role: "assistant",
                content: response.response || "I'm here to help you create a survey. Please describe what you need."
            }]);
        } catch (error: any) {
            toast({
                title: "Chat error",
                description: error.message || "Failed to chat with AI",
                variant: "destructive",
            });
            setMessages([...newMessages, {
                role: "assistant",
                content: "Sorry, I'm having trouble responding. Please try again."
            }]);
        } finally {
            setIsChatting(false);
        }
    };

    return (
        <DashboardLayout>
            <div className="flex flex-col h-[calc(100vh-80px)] max-w-5xl mx-auto p-4 lg:p-6">
                {/* Header */}
                <div className="flex items-center justify-between mb-6">
                    <div className="flex items-center gap-4">
                        <Button variant="ghost" size="icon" onClick={() => navigate('/create')}>
                            <ArrowLeft className="w-5 h-5" />
                        </Button>
                        <div>
                            <h1 className="text-2xl font-bold font-['Space_Grotesk'] flex items-center gap-2">
                                <Sparkles className="w-6 h-6 text-primary" />
                                AI Survey Assistant
                            </h1>
                            <p className="text-muted-foreground text-sm">
                                Powered by Llama 3.1
                            </p>
                        </div>
                    </div>
                </div>

                {/* Chat Container */}
                <Card className="flex-1 flex flex-col overflow-hidden shadow-xl border-primary/10">
                    <div className="flex-1 overflow-y-auto p-6 space-y-6 bg-gradient-to-b from-gray-50/50 to-white">
                        {messages.map((message, index) => (
                            <div
                                key={index}
                                className={`flex gap-4 ${message.role === "user" ? "justify-end" : "justify-start"}`}
                            >
                                {message.role === "assistant" && (
                                    <div className="w-8 h-8 rounded-full bg-primary/10 flex items-center justify-center flex-shrink-0 mt-1">
                                        <Bot className="w-5 h-5 text-primary" />
                                    </div>
                                )}

                                <div
                                    className={`max-w-[80%] rounded-2xl px-6 py-4 shadow-sm ${message.role === "user"
                                            ? "bg-gradient-primary text-white rounded-tr-none"
                                            : "bg-white border rounded-tl-none text-gray-800"
                                        }`}
                                >
                                    <p className="whitespace-pre-wrap leading-relaxed">{message.content}</p>
                                </div>

                                {message.role === "user" && (
                                    <div className="w-8 h-8 rounded-full bg-blue-100 flex items-center justify-center flex-shrink-0 mt-1">
                                        <User className="w-5 h-5 text-blue-600" />
                                    </div>
                                )}
                            </div>
                        ))}

                        {(isChatting || isGenerating) && (
                            <div className="flex gap-4 justify-start">
                                <div className="w-8 h-8 rounded-full bg-primary/10 flex items-center justify-center flex-shrink-0 mt-1">
                                    <Bot className="w-5 h-5 text-primary" />
                                </div>
                                <div className="bg-white border rounded-2xl rounded-tl-none px-6 py-4 shadow-sm flex items-center gap-2">
                                    <Loader2 className="w-4 h-4 animate-spin text-primary" />
                                    <span className="text-sm text-muted-foreground animate-pulse">
                                        {isGenerating ? "Analyzing requirements and generating survey..." : "Thinking..."}
                                    </span>
                                </div>
                            </div>
                        )}
                        <div ref={messagesEndRef} />
                    </div>

                    {/* Input Area */}
                    <div className="p-4 bg-white border-t">
                        <div className="relative flex items-end gap-2 max-w-4xl mx-auto">
                            <Textarea
                                value={input}
                                onChange={(e) => setInput(e.target.value)}
                                onKeyDown={(e) => {
                                    if (e.key === "Enter" && !e.shiftKey) {
                                        e.preventDefault();
                                        handleSendMessage();
                                    }
                                }}
                                placeholder="Describe your survey (e.g., 'Customer satisfaction survey for a coffee shop')..."
                                className="min-h-[60px] max-h-[150px] resize-none pr-12 text-base py-3 rounded-xl border-gray-200 focus:border-primary focus:ring-primary/20"
                                disabled={isChatting || isGenerating}
                                autoFocus
                            />
                            <Button
                                onClick={handleSendMessage}
                                disabled={isChatting || isGenerating || !input.trim()}
                                className="absolute right-2 bottom-2 h-10 w-10 p-0 rounded-lg bg-primary hover:bg-primary/90 transition-all"
                            >
                                <Send className="w-5 h-5 text-white" />
                            </Button>
                        </div>
                        <p className="text-center text-xs text-muted-foreground mt-3">
                            Tip: Say <strong>"done"</strong> when you are ready to generate the survey.
                        </p>
                    </div>
                </Card>
            </div>
        </DashboardLayout>
    );
};

export default AiSurveyAssistant;
